spring.application.name=my_movie_app
server.port=8080

app.base-url=http://localhost:8080

spring.datasource.url=jdbc:postgresql://localhost:5432/movie_booking
spring.datasource.username=admin
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.profiles.active=dev

jwt.secret=mySuperSecretKeyMySuperSecretKey
jwt.expiration=86400000

spring.data.redis.host=localhost
spring.data.redis.port=6379


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=laiyenviet@gmail.com
spring.mail.password=zlldwjtnskjfzmrg

jwt.access-expiration: 900
jwt.refresh-expiration: 604800

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.swagger-ui.path=/swagger-ui.html

spring.security.user.name=admin
spring.security.user.password=123456